Библиотека numpy

In [1]:
# задание 1

import numpy as np

N = int(input('Введите N: '))
first_array = np.array(list(reversed([i for i in range(0, N)])))
print(first_array)

Введите N: 10
[9 8 7 6 5 4 3 2 1 0]


In [2]:
# задание 2

mat = np.diag(first_array)
print(mat)

[[9 0 0 0 0 0 0 0 0 0]
 [0 8 0 0 0 0 0 0 0 0]
 [0 0 7 0 0 0 0 0 0 0]
 [0 0 0 6 0 0 0 0 0 0]
 [0 0 0 0 5 0 0 0 0 0]
 [0 0 0 0 0 4 0 0 0 0]
 [0 0 0 0 0 0 3 0 0 0]
 [0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [3]:
# задание 3

a = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]], float)
b = np.array([[4], [12], [-3]], float)
print(np.linalg.solve(a, b))

[[ 0.46666667]
 [ 3.84444444]
 [-5.55555556]]


In [4]:
# задание 4

user_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 1, 0, 0],
        [0, 0, 0, 2, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], np.int32
)

next_user_stats = np.array([0, 1, 2, 0, 0, 0])

def cos_array(x):
    return np.dot(x, next_user_stats)/(np.linalg.norm(user_stats[0]) * np.linalg.norm(x))

cos_list = list(np.apply_along_axis(cos_array, axis=1, arr=user_stats))

print(user_stats[cos_list.index(max(cos_list))])

[0 1 1 0 0 0]
